name: Deploy Lambda Function

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install node packages
        run: npm install

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: AKIASJA72U525V2HXDXU
          aws-secret-access-key: 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
          aws-region: ap-south-1

      - name: Build Docker Image
        run: docker build -t lambda_cicd .

      - name: Tag Docker Image
        run: docker tag lambda_cicd:latest 156833064821.dkr.ecr.ap-south-1.amazonaws.com/lambda_cicd:latest

      - name: Push Docker Image to ECR
        run: docker push 156833064821.dkr.ecr.ap-south-1.amazonaws.com/lambda_cicd:latest
